<?php
return [
	'in a year'                  => 'in a year',
	'in a year and %m months'    => 'in a year and %m months',
	'in %y years'                => 'in %y years',
	'in a month'                 => 'in a month',
	'in a month and %d days'     => 'in a month and %d days',
	'in %m months'               => 'in %m months',
	'tomorrow'                   => 'tomorrow',
	'in a day and %h hours'      => 'in a day and %h hours',
	'in %d days'                 => 'in %d days',
	'in an hour'                 => 'in an hour',
	'in an hour and %i minutes'  => 'in an hour and %i minutes',
	'in %h hours'                => 'in %h hours',
	'in a minute'                => 'in a minute',
	'in %i minutes'              => 'in %i minutes',
	'a year ago'                 => 'a year ago',
	'a year and %m months ago'   => 'a year and %m months ago',
	'%y years ago'               => '%y years ago',
	'a month ago'                => 'a month ago',
	'a month and %d days ago'    => 'a month and %d days ago',
	'%m months ago'              => '%m months ago',
	'yesterday'                  => 'yesterday',
	'a day and %h hours ago'     => 'a day and %h hours ago',
	'%d days ago'                => '%d days ago',
	'an hour ago'                => 'an hour ago',
	'an hour and %i minutes ago' => 'an hour and %i minutes ago',
	'%h hours ago'               => '%h hours ago',
	'a minute ago'               => 'a minute ago',
	'%i minutes ago'             => '%i minutes ago',
	'just now'                   => 'just now',
	'Y-m-d'                      => 'Y-m-d'
];