<?php
return [
	'in a year'                  => 'en un año',
	'in a year and %m months'    => 'en un año y %m meses',
	'in %y years'                => 'en %y años',
	'in a month'                 => 'en un mes',
	'in a month and %d days'     => 'en un mes y %d días',
	'in %m months'               => 'en %m meses',
	'tomorrow'                   => 'mañana',
	'in a day and %h hours'      => 'en un día y %h horas',
	'in %d days'                 => 'en %d días',
	'in an hour'                 => 'dentro de una hora',
	'in an hour and %i minutes'  => 'en una hora y %i minutos',
	'in %h hours'                => 'en %h horas',
	'in a minute'                => 'en un minuto',
	'in %i minutes'              => 'en %i minutos',
	'a year ago'                 => 'hace un año',
	'a year and %m months ago'   => 'hace un año y %m meses',
	'%y years ago'               => 'hace %y años',
	'a month ago'                => 'hace un mes',
	'a month and %d days ago'    => 'hace un mes y %d días',
	'%m months ago'              => 'hace %m meses',
	'yesterday'                  => 'ayer',
	'a day and %h hours ago'     => 'hace 1 día y %h horas',
	'%d days ago'                => 'hace %d días',
	'an hour ago'                => 'hace une hora',
	'an hour and %i minutes ago' => 'hace une hora y %i minutos',
	'%h hours ago'               => 'hace %h horas',
	'a minute ago'               => 'hace un minuto',
	'%i minutes ago'             => 'hace %i minutos',
	'just now'                   => 'justo ahora',
	'Y-m-d'                      => 'd/m/Y'
];