<?php
return [
	'in a year'                  => 'dans un an',
	'in a year and %m months'    => 'dans un an et %m mois',
	'in %y years'                => 'dans %y ans',
	'in a month'                 => 'dans un mois',
	'in a month and %d days'     => 'dans un mois et %d jours',
	'in %m months'               => 'dans %m mois',
	'tomorrow'                   => 'demain',
	'in a day and %h hours'      => 'dans 1 jour et %h heures',
	'in %d days'                 => 'dans %d jours',
	'in an hour'                 => 'dans une heure',
	'in an hour and %i minutes'  => 'dans une heure et %i minutes',
	'in %h hours'                => 'dans %h heures',
	'in a minute'                => 'dans une minute',
	'in %i minutes'              => 'dans %i minutes',
	'a year ago'                 => 'il y a un an',
	'a year and %m months ago'   => 'il y a un an et %m mois',
	'%y years ago'               => 'il y a %y ans',
	'a month ago'                => 'il y a un mois',
	'a month and %d days ago'    => 'il y a un mois et %d jours',
	'%m months ago'              => 'il y a %m mois',
	'yesterday'                  => 'hier',
	'a day and %h hours ago'     => 'il y a 1 jour et %h heures',
	'%d days ago'                => 'il y a %d jours',
	'an hour ago'                => 'il y a une heure',
	'an hour and %i minutes ago' => 'il y a une heure et %i minutes',
	'%h hours ago'               => 'il y a %h heures',
	'a minute ago'               => 'il y a une minute',
	'%i minutes ago'             => 'il y a %i minutes',
	'just now'                   => '&agrave; l\'instant',
	'yyyy-MM-dd'                 => 'dd/MM/yyyy',
];