<?php
return array (
  'in a year' => 'in un anno',
  'in a year and %m months' => 'in un anno e %m mesi',
  'in %y years' => 'in %anni',
  'in a month' => 'in un mese',
  'in a month and %d days' => 'in un mese e %d giorni',
  'in %m months' => 'in %m mesi',
  'tomorrow' => 'domani',
  'in a day and %h hours' => 'in 1 giorno e %h ore',
  'in %d days' => 'in %d giorni',
  'in an hour' => 'in un\'ora',
  'in an hour and %i minutes' => 'in un\'ora e %i minuti',
  'in %h hours' => 'in %h ore',
  'in a minute' => 'in un minuto',
  'in %i minutes' => 'in %i minuti',
  'a year ago' => 'un anno fa',
  'a year and %m months ago' => 'un anno fa, e %m mesi',
  '%y years ago' => 'ci sono %y anni',
  'a month ago' => 'un mese fa',
  'a month and %d days ago' => 'c\'&egrave; un mese e %d giorni',
  '%m months ago' => 'ci sono %m mesi',
  'yesterday' => 'ieri',
  'a day and %h hours ago' => 'c\'&egrave; di 1 giorno e %h ore',
  '%d days ago' => 'ci sono %d giorni',
  'an hour ago' => 'c\'&egrave; un tempo',
  'an hour and %i minutes ago' => 'c\'&egrave; anche un\'ora e %i minuti',
  '%h hours ago' => 'non c\'&egrave; %h ore',
  'a minute ago' => 'un minuto fa',
  '%i minutes ago' => 'ci sono %i minuti',
  'just now' => 'al momento',
  'Y-m-d' => 'd/m/Y',
);